---
title: "Article 2 : Artificially sweetened drinks may not be heart healthier than sugary drinks"
description: | 
  Second article 
author:
  - name: Emeline Derycke
date: "`r Sys.Date()`"
categories:
  - "English for Science"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## General information 

Source of the article:  [link](https://www.sciencedaily.com/releases/2020/10/201026144524.htm)
  
Date: 26/10/2020
  
Word count : 392

## Vocabulary 
| word from the text  | Synonym/definition in English                             | French translation |
| ------------------- | --------------------------------------------------------- | ------------------ |
| healthier           | to be beter for health                                    | plus sain          |
| relationship        | report between two things                                 | relation           |
| sweeteners          | said of a substance that gives a mild favor               | édulcorants        |
| in addition         | syn: moreover                                             | en outre           |
| to fuel             | syn: to feed                                              | pour alimenter     |
| current             | syn: present                                              | actuel             |
| labeling            | attach a label by tying it with string or sticking it on  | étiquetage         |

## Analysis about the study 
* Researchers:

Université Sorbonne Paris Nord, Inserm, Inrae, Cnam (lead author : Eloi Chazelas, doctorant).

* Published in? when:

Journal of the American College of Cardiology. (26/10/2020)

* General topic:

Sweetened drinks and artificial sweetened drinks are not good for the heart

* Procedure: what was examined:

   + STUDY the relationship between risk of heart disease and the consumption of sweetened and unsweetened drunks, both artificial and not
   + people classified into three categories

* Conclusions:

   + there are still a lot of people who have had an incident of heart disease
   + rtificially sweetened drinks aren’t a good substitute for sweetened drinks

* Remaining questions:

Why people are so attracted to artificial sweetened drinks .
